[project]
name = "biolearn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "equinox>=0.13.4",
    "jax>=0.9.0",
    "numpy>=2.4.1",
]
